runtime: nodejs20

instance_class: F2

env_variables:
  FINNHUB_API_KEY: "co16lppr01qllto43pjgco16lppr01qllto43pk0"
  POLYGON_API_KEY: "CrlZaVcjz8JHnDAhL7DqgtaHg2iBu6K4"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto